### ISSUE TITLE
Hard crash swithcing between worlds.

### ISSUE THREAD

**Issue by zkreeg** [kremnev8/CoreKeeperMods#1]
Using Thunderstore mod manager r2modman to launch the game. The only mods enable are Instant Portal Charge and BepInExPack Core Keeper.

r2modman 3.1.31
Core Keeper v0.4.3
Instant Portal Charge v1.0.0
BepInEx-BepInExPack_Core_Keeper-1.0.0

All mods are installed from https://core-keeper.thunderstore.io/ via 'Install with Mod manager'.

After exiting any worlds  then clicking on a different world the game will crash the moment I click any world in the list. Any world, even the same world I exited from previously. This is reproducible 100% of the time.

**Comment by limoka** [comment]
Unfortunately I don't know the cause of this issue, and debugging hard crashes here is nearly impossible. I have seen it before myself, but fortunately it does not cause any major issues apart from the crash itself.

**Comment by zkreeg** [comment]
It makes switching worlds impossible because it crashes 100% of the time.

"bug wontfix"

That's disappointing. The mod is pointless if it breaks the game and you can't fix it. Which raises the question; What is the point of it being available for download if it's broken and can't be fixed?

**Comment by limoka** [comment]
First of all it's not broken. It works most of the time. And I can't guarantee that it will 100% of the time. Second of all this issue is absolutely not debuggable. When Unity with il2cpp crashes like that it leaves 0 information that would allow me to debug it. Plus I highly suspect it's not even the mod itself that causes the issue, but BepInEx. And it's currently highly experimental for il2cpp. So really if you are using mods you agree that some things can break.

**Comment by zkreeg** [comment]
You are absolutely right. Please excuse my previous reply.  I apologize.

**Comment by limoka** [comment]
I mean thankfully recent updates to BepInEx (We are not using them yet) allow to get more info when game crashes. So maybe eventually I will find the cause of this.
