### ISSUE TITLE
it can not be use in this game version

### ISSUE THREAD

**Issue by sam0324sam** [kremnev8/CoreKeeperMods#6]
PlacementPlus can not be use in this game version.
please update! thanks!

**Comment by limoka** [comment]
My mods have been updated. Thanks for report.

**Comment by Mithalogica** [comment]
Curious about BucketMod, since this is where I land when I follow the link on the mod page; but Thunderstore still lists version 1.0.0, updated a month ago. I can (now) get the game to launch with both PLacement Plue and Bucket Mod enabled, but the table/buckets are nowhere to be crafted. If I recall, one of the new vanilla items took the same crafting slot, perhaps?

**Comment by limoka** [comment]
Unfortunately Bucket uses Json Loader, which in turn uses Custom Entity module, which unfortunately I currently have issues with. As such Bucket Mod is indeed broken. You will have to wait for me to fix that mod.
